example.property: "I AM A PROD PROPERTY usercenter-prod.yml"

server:
  port: 8033



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hereuser?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    testWhileIdle: "true"
    validationQuery: "SELECT 1"



mybatis:
  mapper-locations:
    - classpath:com.usercenter.mapper/*.xml
  type-aliases-package: com.userbase.entity



management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health



logging:
  level:
    com.usercenter.mapper: DEBUG


