example:
  property: "i am a dev property productcenter.yml 001"


server:
  port: 8032



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.26:3306/hereproduct?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456




mybatis:
  mapper-locations:
    - classpath:com.productcenter.mapper/*.xml
  type-aliases-package: com.productcenter.entity



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.26:8761/eureka/



management:
  server:
    port: 8042
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
          - info



logging:
  level:
    com.productcenter.mapper: DEBUG
