example:
  property: "i am a prod property zuulsrv.yml"



server:
  port: 5555



logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG



eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.2.26:8761/eureka/



management:
  server:
    port: 8043
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*" #注意这里*要加引号，暴露全部，也可以只暴露相应endpoint



zuul:
  prefix: /api # 所以已定义的服务，都将添加前缀 /api
  routes:
    usercenterservice:
      serviceId: usercenter
      path: /user/**
    productcenterservice:
      serviceId: productcenter
      path: /product/**


